### ISSUE TITLE
Can't use Number row

### ISSUE THREAD

**Issue by Andorahfal** [ThornyFFXI/tHotBar#10]
I am using this on 2 different servers. On one, I have no issues using the number row to chat, On another server, when I try to type in chat, it does nothing when I press 1 through 0, also with +shift for symbols. If I unload THorBar, it works fine. I copied the addons/thotbar and config/addons/thotbar (and renamed the folder to correct character) from the working server, and still nothing. The addon itself works perfectly fine, its just that its blocking me from typing. Using the numpad for numbers does work.

**Comment by ThornyFFXI** [comment]
Nothing to do with thotbar, you have different ashita settings.  While ingame on the server it doesn't work on, type '/ashita' then look under input manager for the setting: Block Keybinds During Game Input.  Turn it on.

**Comment by Andorahfal** [comment]
That did fix it, but why did the number row work if I did "/addon unload thotbar"?

**Comment by ThornyFFXI** [comment]
Thotbar sets ashita binds when loaded, and unsets them when unloaded.  It is intended to obey the setting in Ashita.
