### ISSUE TITLE
Can't type numbers in chat?

### ISSUE THREAD

**Issue by jmbauer3** [ThornyFFXI/tHotBar#12]
Hello!

I'm not sure if this is a bug or things working as intended, but trying to use the number row while in the chatbox still uses the hotbar buttons. The numpad still works but that's kind of an awkward workaround when typing.

I love this addon though! Making macros was making my head spin, but having an actual interface for it helps me immensely.

Cheers!

**Comment by ThornyFFXI** [comment]
same issue as here:
https://github.com/ThornyFFXI/tHotBar/issues/10

change the ashita setting

**Comment by jmbauer3** [comment]
That was indeed it! Thank you for the help!
