### ISSUE TITLE
Minor issue with recast display when > 1 hour recast time

### ISSUE THREAD

**Issue by bigsoph** [ThornyFFXI/tHotBar#2]
I am using the interface 4.14 release. 

It appears that when a recast timer is formatted as hh:mm that the minutes portion of the display is currently showing the entire remaining recast in minutes, rather than accounting for any hours shown in the hours portion of the display.

For example immediately after casting a 2 hour ability, at which point the recast time of the 2 hour ability is 119 minutes, the recast timer will be displayed as "1:119" rather than having accounted for the hours display and showing "1:59".

**Comment by ThornyFFXI** [comment]
This has been fixed in 1.12.
