### ISSUE TITLE
Crashes when typing custom commands

### ISSUE THREAD

**Issue by phughlett** [ThornyFFXI/tHotBar#3]
Not sure if there is a workaround, but I'm trying to set up multiline macros such as:

```
/ja "Sneak Attack" <me>
/wait 1
/ja "Trick Attack" <me>
```

But while I'm typing my game crashes.  Sometimes it saves, sometimes not.  Any insight?

**Comment by evodude717** [comment]
I have also been having this issue. Sometimes I can get lucky if I copy/paste what I want to add from notepad but it's usually a 50/50 crapshoot if it crashes or not. I updated to the newest version but it still does it.

**Comment by ThornyFFXI** [comment]
This is a bug in imgui textboxes from Ashita 4.14.  Updating Ashita itself to 4.15 will resolve it.  Note that this will require you to update all plugins as well.

**Comment by phughlett** [comment]
Thanks for the information.
