### ISSUE TITLE
Auto Translate text

### ISSUE THREAD

**Issue by Andorahfal** [ThornyFFXI/tHotBar#6]
Is there a way to put Auto translate text into the text field?

**Comment by ThornyFFXI** [comment]
No, auto-translate uses unique shift-JIS escape codes and is not compatible with the text format used by imgui.  I've considered a few solutions to this, perhaps the most feasible would be a seperate addon that watches for text in a specific format, such as enclosed in double brackets: [[Please invite me.]] and automatically converts it to the shift-jis.  I'll leave the issue open as a reminder, but it isn't something that will be built directly into tHotBar and probably will not be in the immediate future.

**Comment by Andorahfal** [comment]
Ok, thank you

**Comment by ThornyFFXI** [comment]
Another user has created an addon of this nature, you can access it at:
https://github.com/m4thmatic/translataru/
