### ISSUE TITLE
Installation seems correct, can't load the Addon

### ISSUE THREAD

**Issue by njoy1989** [ThornyFFXI/tHotBar#8]
Hey Thorny ~

First of all, thanks for creating this addon :)

I downloaded the release ZIP and extracted the file as instructed.
It seems everything fell into place, however when trying to load the addon it says:

Failed to load plugin "thotbar". Reason: Load Libary A failed.
Error Message: The plugin could not be found.

Are there currently any known issues? Please see attached the installation path.
![Uploading Installation Path.jpg…]()

**Comment by ThornyFFXI** [comment]
Addons are loaded with `/addon load thotbar`, it seems you used `/load thotbar`, which would be for loading a plugin.

**Comment by njoy1989** [comment]
That was it, thanks so much for the quick reply :)
